language: rust
os:
  - linux
  # - osx
rust:
  - nightly
notifications:
  email: false
before_script:
  - cargo +nightly install rustfmt-nightly --force
  # - cargo +nightly install clippy --force
  - export PATH=$PATH:~/.cargo/bin
script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo +nightly fmt -- --write-mode=diff
  # - cargo +nightly clippy -- --deny warnings
